[package]
name = "wtp"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
rand = "0.9.2"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
